Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_check_update = false

  config.vm.define "maissatS" do |server|
    server.vm.hostname = "maissatS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.name   = "maissatS"
      vb.memory = 1024
      vb.cpus   = 1
    end

    server.vm.synced_folder "confs", "/vagrant_confs"
    server.vm.provision "shell", path: "scripts/server.sh"
  end
end